### ISSUE TITLE
Move to PauseAI org

### ISSUE THREAD

**Issue by joepio** [Maximophone/ProjectBot#1]
Hi Maxime! Would it be OK for you to move this over to the PauseAI github organization?

**Comment by Maximophone** [comment]
Yes

**Comment by Maximophone** [comment]
Just tried, I think I need to be given a role in the pauseai organisation to be allowed to do this. I don't have permission to create public repositories on PauseAI

**Comment by joepio** [comment]
invite sent

**Comment by joepio** [comment]
Thanks
