### ISSUE TITLE
Make the publishing of actions on the "i-did-a-thing" channel optional

### ISSUE THREAD

**Issue by Maximophone** [Maximophone/ProjectBot#3]
At the moment, when someone fills in the action form, which populates an airtable database, the bot automatically publishes the action to the "i-did-a-thing" channel on discord.
We would like to add a tickbox to the form to make this optional.

Todo:
- Modify the airtable to add a checkbox column
- Modify the form to add the checkbox
- Add a condition in the bot to check this before publishing the action

**Comment by Maximophone** [comment]
I have added a boolean column called "publish" to airtable

**Comment by joepio** [comment]
I think the message could contain more sensitive stuff if it's toggle-able / opt-in (like the recipient name / org name)
